### ISSUE TITLE
Diagramar Entidad / Relación en PostgreSQL

### ISSUE THREAD

**Issue by mchalin** [CodeSystem2022/ProyectoIntegrador_TercerSemestre_UTN_BsAs#4]

**Comment by mchalin** [comment]
Asignado a Viviana

**Comment by vmgith** [comment]
DER  presentado. En revision del equipo
[DER_SistemaVEntas.pdf](https://github.com/CodeSystem2022/ProyectoIntegrador_TercerSemestre_UTN_BsAs/files/11580335/DER_SistemaVEntas.pdf)

**Comment by mchalin** [comment]
Vivi, chequeate estas modificaciones! 



![Image](https://github.com/CodeSystem2022/ProyectoIntegrador_TercerSemestre_UTN_BsAs/assets/94797028/8a2aa66a-73f0-418e-93f0-c181727ecdfb)
