### ISSUE TITLE
Generar script para la creacion inicial de la base de datos

### ISSUE THREAD

**Issue by mchalin** [CodeSystem2022/ProyectoIntegrador_TercerSemestre_UTN_BsAs#7]
Necesitamos la query sql para que, cuando inicialice el programa, sino existe la tabla, la cree

**Comment by vmgith** [comment]
Script para la creacion de la base VENTAS y las tablas :usuarios,clientes,productos,ventas,ventasitems



[script .txt](https://github.com/CodeSystem2022/ProyectoIntegrador_TercerSemestre_UTN_BsAs/files/11595178/script.txt)
no permite subir archivos con extension sql. renombrarlo
